---
- hosts: all
  become: yes

  vars:
    # Vars can also be passed in via CLI with `--extra-vars="name=value"`.
    node_apps_location: /usr/local/opt/node

  roles:
    - role: jdauphant.nginx
      nginx_http_params:
        - sendfile "on"
        - access_log "/var/log/nginx/access.log"
      nginx_sites:
        default:
         - listen 80
         - location / { proxy_pass http://localhost:3000; }  
     
    - role: ssh-keys
      tag: ssh

    - role: default-apps
      tag: apps

    - role: geerlingguy.nodejs
      tag: nodejs
      nodejs_version: "8.x"

    - role: networking
      tag: networking

    - role: deploy-app
      tag: deploy

  tasks:
    - name: Set a hostname
      hostname:
        name: "webserver"

    - name: add hostname to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1[ \t]+localhost'
        line: '127.0.0.1 localhost webserver'
        state: present